// Build script for the patcher.
// 1. Embed payload JS files as string constants
// 2. esbuild-bundle the patcher into a single CJS file
// 3. pkg-compile the bundle into a Windows .exe (and optionally macOS too)
//
// Usage:
//   node build.js              # build for current platform's target  (default: win-x64)
//   node build.js --targets node22-win-x64,node22-macos-x64,node22-macos-arm64
//
// Output: dist/

'use strict';

const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');

const ROOT = __dirname;
const DIST = path.join(ROOT, 'dist');
const SRC = path.join(ROOT, 'src');
const PAYLOAD_SRC = path.join(SRC, 'payload');

function ensureDir(p) { fs.mkdirSync(p, { recursive: true }); }
function read(p) { return fs.readFileSync(p, 'utf8'); }

// --- 1. Embed payload sources ---------------------------------------------

ensureDir(DIST);

const payloadHookSrc    = read(path.join(PAYLOAD_SRC, 'rtl-fix-hook.js'));
const payloadPayloadSrc = read(path.join(PAYLOAD_SRC, 'rtl-fix-payload.js'));

const embedded = `// AUTO-GENERATED by build.js. Do not edit.
'use strict';
module.exports = {
  RTL_FIX_HOOK_SOURCE:    ${JSON.stringify(payloadHookSrc)},
  RTL_FIX_PAYLOAD_SOURCE: ${JSON.stringify(payloadPayloadSrc)},
};
`;
fs.writeFileSync(path.join(DIST, 'embedded-payloads.js'), embedded);
console.log('[build] embedded payload sources →', path.join(DIST, 'embedded-payloads.js'));

// --- 2. esbuild bundle the patcher ----------------------------------------

const esbuild = require('esbuild');

async function bundle() {
  await esbuild.build({
    entryPoints: [path.join(SRC, 'patch.js')],
    bundle: true,
    platform: 'node',
    target: 'node22',
    format: 'cjs',
    outfile: path.join(DIST, 'patcher.bundled.js'),
    external: [],
    alias: {
      'embedded-payloads': path.join(DIST, 'embedded-payloads.js'),
    },
    plugins: [{
      name: 'fix-import-meta-url',
      setup(build) {
        const fsLocal = require('fs');
        // @electron/asar passes import.meta.url to module.createRequire().
        // createRequire accepts a plain path string just fine, so replace with
        // __filename directly — no require()/url-module dance, no rename risk.
        build.onLoad({ filter: /\.[cm]?js$/ }, (args) => {
          let src = fsLocal.readFileSync(args.path, 'utf8');
          if (src.includes('import.meta.url')) {
            src = src.replace(/import\.meta\.url/g, '__filename');
          }
          return { contents: src, loader: 'js' };
        });
      },
    }],
    banner: { js: '/* claude-rtl-fix patcher (bundled) */' },
    minify: false,
    sourcemap: false,
    logLevel: 'info',
  });
  console.log('[build] bundled →', path.join(DIST, 'patcher.bundled.js'));
}

bundle().then(() => {
  console.log('[build] dist/patcher.bundled.js ready.');
  console.log('[build] To produce the Windows .exe, run build-windows.cmd on a Windows machine with Node 22.');
}).catch((e) => {
  console.error('[build] failed:', e.message);
  process.exit(1);
});
console.log('[build] bundled →', path.join(DIST, 'patcher.bundled.js'));

// --- 3. Build Windows .exe via Node SEA -----------------------------------
//
// Done in a separate script (build-windows.cmd) that runs on Windows because:
//   - nodejs.org isn't reachable from all build environments
//   - postject needs a Windows node.exe to inject into
//
// See build-windows.cmd in this directory. After running this build.js (which
// produces dist/patcher.bundled.js + dist/embedded-payloads.js), copy the dist
// folder to a Windows machine that has Node 22 installed, and run
// build-windows.cmd. It downloads node.exe, generates the SEA blob, postjects,
// and emits dist/claude-rtl-patch.exe.


